### ISSUE TITLE
Liquidator should be able to specify multiple rewards

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1129]
`Reward` is a collateral denom a liquidator selects to receive when he liquidates an unhealthy borrow position.

Today, we only accept liquidation with only one selected reward. However, it may happen that liquidator has to select few collaterals to cover his repayment.

**Example**: Alice has the following tokens (in USD value) as a collateral: $100A, $200B, $500C. She borrows $1000X. After some time X market value drops and liquidation happens and we need to liquidate $400 of her collateral. Let's assume that value of A B and C was relatively stable (so we won't get into bad collateral discussion here). Liquidator will like to receive A, B and C in that order of preference. So, we need to change the `MsgLiquidate`:

```
repeated Coin reward = 4 [(gogoproto.nullable) = false];
```

**Comment by toteki** [comment]
I prefer we close this - since all the calculations (direct liquidation fee, prices, repayment amount, close factor, bad debt) would have to be chained like the two (or more) collateral liquidations were separate events, sending them in one message wouldn't add significant value. Liquidators can use separate transactions if one collateral type is exhausted.
