### ISSUE TITLE
Optimize Build Docker Image e2e tests

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1356]
## Summary

In `e2e` tests, the `make docker-build-debug` step takes 7-8min!
That's definitely too long and sometimes creates timeouts.

We need to optimize it

## Proposal

Proposed solution: 
+ register built image, eg on: ghcr.io

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by gsk967** [comment]
while doing `e2e` they are building the all binaries (umeed/price-feeder/peggo) , instead of building each one we wll create new docker image whenever new tag is released

1. umee docker (https://github.com/umee-network/umee/pull/1489)
2. price-feeder (https://github.com/umee-network/umee/pull/1489)
3. peggo (https://github.com/umee-network/peggo/pull/385)

Note:
> Now above three binaries will be separated docker images
