### ISSUE TITLE
Testnet validator hitting consensus failure 

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#852]
## Summary of Bug

One of our testnet validators (commonly referred to as banana) is unable to reach consensus. 

These are our logs : 

```
Apr 28 00:04:08 banana umeed[28168]: 12:04AM INF ABCI Handshake App Info hash="\x1c�Ŀ?Z��\x13���b�՞��o�4T��K3\b�\x16�-�" height=343827 module=consensus protocol-version=0 software-version=

Apr 28 00:04:08 banana umeed[28168]: 12:04AM INF ABCI Replay Blocks appHeight=343827 module=consensus stateHeight=343827 storeHeight=343828

Apr 28 00:04:08 banana umeed[28168]: 12:04AM INF Replay last block using real app module=consensus

Apr 28 00:04:08 banana umeed[28168]: Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 1CB4C4BF3F5AB4F113A3B2DB62AAD59E91D56FA03454868E4B3308CA16882D8F, got AE4F31CB30612BFDDC35909455A5889A9084E87BE163B0B12308AF9FD3A21C5E
```

Wondering if this is related to #826 🤔 would love your input when you get the chance @facundomedica 

## Version

v2.0.0

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by facundomedica** [comment]
Somehow I missed this issue! Do we have more logs? Is this something reproducible? Different binaries? We solved it just by restarting?
I'll stick around until this one gets solved, it overlaps with my next position anyway :)

**Comment by toteki** [comment]
It's still down (now jailed) and in a loop trying to restart itself I believe - [see active / jailed validators](https://explorer.umeemania-1.network.umee.cc/umee/staking)

I haven't checked the logs, so the error message above from Woz is what we have to go on currently

**Comment by adamewozniak** [comment]
Hey @facundomedica ! Ping me on this when you get some time pls - we're able to repro by trying to sync up the validator node which is having issues 😄

**Comment by facundomedica** [comment]
Hello! Ok, what we need to do there is to be able to run a custom binary in order to debug the issue. I can do it, although I'll need some time.
BTW, are we using the v2.0.1 release or some arbitrary commit? If we are not running a different binary, then I'm pretty sure it will be something related to the issue I was hitting the other day.

My plan is to compile something that contains a bunch of log statements locally (hopefully cross-compiling works fine) and scp-it to the server. And then repeat that a hundred times until we find the root cause lol

(I think I still have access to the server, I'll ping you if I don't)

**Comment by adamewozniak** [comment]
> Hello! Ok, what we need to do there is to be able to run a custom binary in order to debug the issue. I can do it, although I'll need some time. BTW, are we using the v2.0.1 release or some arbitrary commit? If we are not running a different binary, then I'm pretty sure it will be something related to the issue I was hitting the other day.
> 
> My plan is to compile something that contains a bunch of log statements locally (hopefully cross-compiling works fine) and scp-it to the server. And then repeat that a hundred times until we find the root cause lol
> 
> (I think I still have access to the server, I'll ping you if I don't)

We're running v2.0.0 on that, planning to upgrade all testnet nodes to 2.0.1 after you have the chance to check this out 😄

**Comment by facundomedica** [comment]
@adamewozniak I think we should upgrade to v2.0.1 (swap the binary) in this node and see what happens. If the other nodes are running 2.0.1 and this one is running 2.0.0 then there's a good chance that the cause is something in the code that changed.

- If upgrading from 2.0.0 to 2.0.1 fixes the issue, then we know 2.0.1 is actually breaking (!!!)
- If upgrading doesn't work, then there's another issue going on that's present in both 2.0.0 and 2.0.1

**Comment by adamewozniak** [comment]
> @adamewozniak I think we should upgrade to v2.0.1 (swap the binary) in this node and see what happens. If the other nodes are running 2.0.1 and this one is running 2.0.0 then there's a good chance that the cause is something in the code that changed.
> 
> 
> 
> - If upgrading from 2.0.0 to 2.0.1 fixes the issue, then we know 2.0.1 is actually breaking (!!!)
> 
> - If upgrading doesn't work, then there's another issue going on that's present in both 2.0.0 and 2.0.1

Agreed. Most of 2.0.1 is dep updates - whenever @dreamcodez has time we'll do this 🔥

**Comment by adamewozniak** [comment]
Is this still ongoing @dreamcodez ?

**Comment by robert-zaremba** [comment]
We will try to look again at this during the beta tests (if we will have time for that). That happened on ashera

**Comment by robert-zaremba** [comment]
It seams this is solved, and probably could be caused by the RC1 issue we had recently.
